#125 Take Alternate Repo New Name from Change Object
self-xdsd/self-pm pull request #126
Opened 2021-08-30 12:59 UTC by criske

PR for #125

2021-08-30 12:59 UTC, zoeself commented
@criske thank you for your Pull Request. I'll assign someone to review it soon.

2021-08-30 13:08 UTC, zoeself commented
@amihaiemil I couldn't find any assignee for this task. This is either because there are no contributors with role ``REV`` available or because the project does not have enough funds.

Please, make sure there is at least one available contributor with the required role and the project can afford to pay them.

2021-08-31 09:03 UTC, amihaiemil requested changes

2021-08-31 09:03 UTC, amihaiemil commented on src/main/java/com/selfxdsd/selfpm/Webhooks.java
> +                    }
@criske it should be the other way: first look for ``changes.repository`` and if the full name is not found there, take it from ``repository.full_name``. 

Also please write a TODO for adding a unit test or two for this change :D

2021-09-01 08:46 UTC, amihaiemil commented
@criske looks good, thanks!

2021-09-01 08:47 UTC, amihaiemil commented
@rultor merge it please

2021-09-01 08:47 UTC, rultor commented
> @rultor merge it please

@amihaiemil OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/24993-910074042)

2021-09-01 08:50 UTC, merged

2021-09-01 08:50 UTC, rultor commented
> @rultor merge it please

@amihaiemil Done! FYI, the full log is [here](https://www.rultor.com/t/24993-910074042) (took me 3min)